# Generated by Django 5.2.5 on 2025-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='device_id',
            field=models.CharField(choices=[('device-1', 'Device 1'), ('device-2', 'Device 2'), ('device-3', 'Device 3'), ('device-4', 'Device 4')], max_length=20),
        ),
    ]
